CREATE TABLE IF NOT EXISTS products (
    id UUID NOT NULL,

    name CHARACTER VARYING(255) NOT NULL,
    url CHARACTER VARYING(255) NOT NULL,
    price FLOAT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    users_id UUID NOT NULL,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT products_pk PRIMARY KEY (id)
);